import { fontProviders } from "astro/config";
import { Site } from "../../site.config";
import path from "path";
import fs from "fs";

// Adobe Font Provider
const adobeProvider = (config) => {
  const base = fontProviders.adobe(config);
  return {
    name: base.name,
    config: base.config,
    async init(context) {
      await base.init(context);
    },
    async resolveFont({ familyName, weights, styles, subsets, formats, options }) {
      const list = await base.listFonts();
      const match = list?.find(f => f.trim() === familyName.trim()) || familyName;
      return await base.resolveFont({ familyName: match, weights, styles, subsets, formats, options });
    },
    async listFonts() {
      return await base.listFonts();
    }
  };
};

// Helper to transform font name to CSS variable format (e.g. "Roboto Condensed" -> "--face-roboto-condensed")
const toCssVariable = (name) => {
  return `--face-${name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")}`;
};

// Helper to convert Adobe variation code (e.g. "n7", "i4") to numeric weight
const mapVariationToWeight = (variation) => {
  const weightDigit = variation.substring(1);
  if (/^[1-9]$/.test(weightDigit)) {
    return `${weightDigit}00`;
  }
  return '400';
};

// Helper to fetch and cache Adobe Kit data
const getAdobeKitData = async (projectId) => {
  if (!projectId) return null;
  const cacheDir = path.resolve('./src/assets/fonts');
  const cacheFile = path.join(cacheDir, '.adobe-kit-cache.json');

  // Ensure cache directory exists
  if (!fs.existsSync(cacheDir)) {
    fs.mkdirSync(cacheDir, { recursive: true });
  }

  // Attempt to fetch fresh kit data from Typekit API
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 5000);
    const response = await fetch(`https://typekit.com/api/v1/json/kits/${projectId}/published`, {
      headers: { 'Accept': 'application/json' },
      signal: controller.signal
    });
    clearTimeout(timeoutId);

    if (response.ok) {
      const data = await response.json();
      fs.writeFileSync(cacheFile, JSON.stringify(data, null, 2), 'utf-8');
      return data;
    }
  } catch (err) {
    console.warn(`[Astro Font Config] Failed to fetch Adobe Kit data from API: ${err.message}. Trying cache fallback...`);
  }

  // Fallback to cache file if network fetch fails
  if (fs.existsSync(cacheFile)) {
    try {
      const cachedData = JSON.parse(fs.readFileSync(cacheFile, 'utf-8'));
      console.log(`[Astro Font Config] Successfully loaded Adobe Kit data from cache.`);
      return cachedData;
    } catch (err) {
      console.error(`[Astro Font Config] Failed to read cached Adobe Kit data: ${err.message}`);
    }
  }

  return null;
};

// Helper to generate the Fonts.astro component dynamically
const generateFontsComponent = (fontsList) => {
  const componentPath = path.resolve('./src/components/layout/Fonts.astro');
  const dirPath = path.dirname(componentPath);

  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }

  const tags = fontsList.map(font => `    <Font cssVariable="${font.cssVariable}" preload />`).join('\n');

  const content = `---
// This file is auto-generated by astro.config.mjs. Do not edit manually.
import { Font } from "astro:assets";
---
${tags}
`;

  let existingContent = '';
  if (fs.existsSync(componentPath)) {
    existingContent = fs.readFileSync(componentPath, 'utf-8');
  }

  if (existingContent.trim() !== content.trim()) {
    fs.writeFileSync(componentPath, content, 'utf-8');
    console.log(`[Astro Font Config] Auto-generated Fonts.astro containing ${fontsList.length} font(s).`);
  }
};

// Main entry point to resolve and build the font configurations
export async function getResolvedFonts() {
  const resolvedFonts = [];

  // 1. Map Google Fonts from Site Config
  if (Array.isArray(Site.GoogleFonts)) {
    for (const font of Site.GoogleFonts) {
      if (font.family) {
        resolvedFonts.push({
          provider: fontProviders.google(),
          name: font.family,
          cssVariable: toCssVariable(font.family),
          weights: font.weights || ['400']
        });
      }
    }
  }

  // 2. Fetch/Cache and Map Adobe Fonts from Site Config
  if (Site.AdobeWebProjectId) {
    const kitData = await getAdobeKitData(Site.AdobeWebProjectId);
    if (kitData && kitData.kit && Array.isArray(kitData.kit.families)) {
      const providerInstance = adobeProvider({ id: Site.AdobeWebProjectId });
      for (const family of kitData.kit.families) {
        if (family.name) {
          const nameTrimmed = family.name.trim();
          const weights = Array.isArray(family.variations)
            ? [...new Set(family.variations.map(mapVariationToWeight))].sort()
            : ['400'];
          resolvedFonts.push({
            provider: providerInstance,
            name: nameTrimmed,
            cssVariable: toCssVariable(nameTrimmed),
            weights: weights
          });
        }
      }
    }
  }

  // 3. Generate the preloading Fonts.astro component
  generateFontsComponent(resolvedFonts);

  return resolvedFonts;
}
